#include<iostream>
using namespace std;
main() {
	cout <<"Number 1: ";
	float num1;
	cin>> num1;
	cout <<"Number 2: ";
	float num2;
	cin>> num2;
	cout <<"Number 3: ";
	float num3;
	cin>> num3;
	cout <<"Number 4: ";
	float num4;
	cin>> num4;
	cout <<"Number 5: ";
	float num5;
	cin>> num5;
	cout <<"Number 6: ";
	float num6;
	cin>> num6;
	cout <<"Number 7: ";
	float num7;
	cin>> num7;
	cout <<"Number 8: ";
	float num8;
	cin>> num8;
	cout <<"Number 9: ";
	float num9;
	cin>> num9;
	cout <<"Number 10: ";
	float num10;
	cin>> num10;
	cout <<"Number 11: ";
	float num11;
	cin>> num11;
	cout <<"Number 12: ";
	float num12;
	cin>> num12;
	cout <<"Number 13: ";
	float num13;
	cin>> num13;
	cout <<"Number 14: ";
	float num14;
	cin>> num14;
	cout <<"Number 15: ";
	float num15;
	cin>> num15;
	float sum5;
	sum5 = num1 + num2 + num3 + num4 + num5;
	float mul5;
	mul5 = num6 * num7 * num8 * num9 * num10;
	float sub5;
	sub5 = num11 - num12 - num13 - num14 - num15;
	float ma;
	ma = (sum5+mul5)-sub5;
	cout <<"The final result is: "<<ma;
	}